[settings]
experimental = true
legacy_version_file_disable_tools = ['terraform']

[tools]
terraform = "1.14.6"
trivy = "0.69.1"
terraform-docs = "0.21.0"
pre-commit = "4.5.1"
tflint = "0.61.0"
direnv = "2.37.1"
